### PR TITLE
Adjusted name input prompt

### PR DESCRIPTION
**Pull request by 0-BSCode**

### CODE REVIEW

**Review by kulaizki — CHANGES_REQUESTED** [review]
This is a remarkable adjustment, @0-BSCode! However, I believe that "beautiful" is synonymous with "handsome." Could you revise this to use a more universal adjective instead of using both, but without using the word "beautiful"?

**Comment by 0-BSCode** [comment]
> This is a remarkable adjustment, @0-BSCode! However, I believe that "beautiful" is synonymous with "handsome." Could you revise this to use a more universal adjective instead of using both, but without using the word "beautiful"?

Sure thing!

**Comment by 0-BSCode** [comment]
I changed the adjective to "distinguished" @kulaizki . Will this do?

**Comment by kulaizki** [comment]
> I changed the adjective to "distinguished" @kulaizki . Will this do?

LGTM! Feel free to merge when ready.

**Review by kulaizki — APPROVED** [review]

**Pull request merged**
